name: Run Todoist Automation

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 5 * * *" # Daily at 5 AM UTC (midnight EST)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install necessary dependencies
      - name: Install dependencies
        run: npm install @doist/todoist-api-typescript

      # Step 4: Run the automation script
      - name: Run Todoist Automation Script
        run: node todoist_automation.js
        env:
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
