name: Run Todoist Automation Script

on:
  # Schedule: Runs every day at midnight EST (convert to UTC)
  schedule:
    - cron: '0 5 * * *' # Midnight EST = 5:00 AM UTC

  # Allow manual runs
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Todoist Automation Script
        env:
          TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
        run: node todoist_automation.mjs
